services:
  fastapi-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app  # Définit le PYTHONPATH pour que FastAPI trouve les modules
    depends_on:
      - postgres
    networks:
      - data

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pandora_user
      POSTGRES_PASSWORD: pandora_user
      POSTGRES_DB: pandora_db
    networks:
      - data

#  react-native:
#    build:
#      context: ./client  # Dossier du projet React Native
#      dockerfile: Dockerfile  # Dockerfile pour le service React Native
#    volumes:
#      - ./client:/app  # Monte le dossier client dans /app du conteneur
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ~/.android:/root/.android
#    ports:
#      - "8081:8081"  # Mappe le port 8081 pour le serveur Metro
#    environment:
#      - NODE_ENV=development  # Définit l'environnement de développement
#    networks:
#      - data
#    depends_on:
#      - fastapi-backend  # Assure que le backend FastAPI démarre d'abord

volumes:
  postgres_data:

networks:
  data:
