services:
  fastapi-backend:
    build:
      context: ./server  # Contexte de construction du dossier server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app  # Monte le dossier server dans /app du conteneur
    ports:
      - "8000:8000"  # Mappe le port 8000 du conteneur au port 8000 de l'hôte
    environment:
      - PYTHONPATH=/app  # Définit le PYTHONPATH pour que FastAPI trouve les modules
    depends_on:
      - postgres
    networks:
      - data

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pandora_user
      POSTGRES_PASSWORD: pandora_user
      POSTGRES_DB: pandora_db
    networks:
      - data

volumes:
  postgres_data:
networks:
  data: